export const DAILY_TOPICS = [
  "How the Sun Works",
  "Why the Sky is Blue",
  "How Airplanes Fly",
  "The Water Cycle",
  "How Vaccines Work",
  "Why We Dream",
  "How the Internet Works",
  "Black Holes",
  "How Batteries Work",
  "Photosynthesis",
  "Why the Ocean is Salty",
  "How Earthquakes Happen",
  "DNA and Genetics",
  "How Magnets Work",
  "The Human Heart",
  "How Computers Think",
  "Why Leaves Change Color",
  "How Rockets Work",
  "The Speed of Light",
  "How Memory Works",
  "Gravity",
  "How Clouds Form",
  "The Ice Ages",
  "How Sound Travels",
  "Why We Need Sleep",
  "How Volcanoes Erupt",
  "The Solar System",
  "How WiFi Works",
  "Why We Laugh",
  "How Bridges are Built",
  "Electricity",
  "How the Eye Sees",
  "The Big Bang",
  "How Cars Work",
  "Why the Moon Changes Shape",
  "How Rainbows Form",
  "The Human Brain",
  "How GPS Works",
  "Why Seasons Change",
  "How Plants Grow",
  "The Periodic Table",
  "How Movies are Made",
  "Tectonic Plates",
  "How Music Affects the Brain",
  "The Immune System",
  "How Rivers Form",
  "Artificial Intelligence",
  "How Lightning Works",
  "The Amazon Rainforest",
  "How Ships Float",
  "Evolution",
  "How 3D Printers Work",
  "The Northern Lights",
  "How the Ear Hears",
  "Cryptocurrency",
  "How Telescopes Work",
  "The Digestive System",
  "How Tornadoes Form",
  "The Great Wall of China",
  "How Touchscreens Work",
  "Coral Reefs",
  "How Radar Works",
  "The Roman Empire",
  "How Blood Flows",
  "Time Zones",
  "How X-Rays Work",
  "The Deep Ocean",
  "How Satellites Orbit",
  "Climate Change",
  "How QR Codes Work",
  "The Human Skeleton",
  "How Dams Work",
  "Dinosaurs",
  "How Fiber Optics Work",
  "The Pyramids of Egypt",
  "How Antibiotics Work",
  "Tides and the Moon",
  "How Video Games are Made",
  "The Nervous System",
  "How Wind Turbines Work",
  "Ancient Greece",
  "How Your Phone Works",
  "Plate Tectonics",
  "How Bees Make Honey",
  "The Industrial Revolution",
  "How MRI Machines Work",
  "Ecosystems",
  "How Encryption Works",
  "The Space Station",
  "How Muscles Work",
  "Supply and Demand",
  "How Solar Panels Work",
  "The French Revolution",
  "How Cameras Work",
  "Probability",
  "How Nuclear Energy Works",
  "The Human Eye",
  "How Maps are Made",
  "Algebra",
  "How Submarines Work",
  "The Renaissance",
];

export function getDailyTopic(): { topic: string; slug: string; date: string } {
  const date = new Date().toISOString().slice(0, 10);
  let hash = 0;
  for (let i = 0; i < date.length; i++) {
    hash = ((hash << 5) - hash) + date.charCodeAt(i);
    hash |= 0;
  }
  const index = Math.abs(hash) % DAILY_TOPICS.length;
  const topic = DAILY_TOPICS[index];
  const slug = topic.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  return { topic, slug, date };
}
